# Generated by Django 5.0.7 on 2024-07-28 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdata',
            table='tb_users',
        ),
    ]
